# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: ThaUnknown.Miru
PackageVersion: 3.1.21
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2022-10-24
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ThaUnknown/miru/releases/download/v3.1.21/win-Miru-3.1.21.exe
  InstallerSha256: B3C8C466F6996799CB079E897CD78182AFAF9D77315B8878A24E62E5909E3292
ManifestType: installer
ManifestVersion: 1.2.0
